/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Waybills;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillsRecord extends UpdatableRecordImpl<WaybillsRecord> implements Record3<Long, Long, Date> {

    private static final long serialVersionUID = 1930387337;

    /**
     * Setter for <code>public.waybills.org_send_id</code>.
     */
    public WaybillsRecord setOrgSendId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.waybills.org_send_id</code>.
     */
    public Long getOrgSendId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.waybills.number</code>.
     */
    public WaybillsRecord setNumber(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.waybills.number</code>.
     */
    public Long getNumber() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.waybills.date</code>.
     */
    public WaybillsRecord setDate(Date value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.waybills.date</code>.
     */
    public Date getDate() {
        return (Date) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Date> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Date> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Waybills.WAYBILLS.ORG_SEND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Waybills.WAYBILLS.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Waybills.WAYBILLS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getOrgSendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOrgSendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord value1(Long value) {
        setOrgSendId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord value2(Long value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord value3(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord values(Long value1, Long value2, Date value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillsRecord
     */
    public WaybillsRecord() {
        super(Waybills.WAYBILLS);
    }

    /**
     * Create a detached, initialised WaybillsRecord
     */
    public WaybillsRecord(Long orgSendId, Long number, Date date) {
        super(Waybills.WAYBILLS);

        set(0, orgSendId);
        set(1, number);
        set(2, date);
    }
}
