/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations implements Serializable {

    private static final long serialVersionUID = 2144410838;

    private final Long   id;
    private final String name;
    private final Long   inn;
    private final Long   settlementAcc;

    public Organizations(Organizations value) {
        this.id = value.id;
        this.name = value.name;
        this.inn = value.inn;
        this.settlementAcc = value.settlementAcc;
    }

    public Organizations(
        Long   id,
        String name,
        Long   inn,
        Long   settlementAcc
    ) {
        this.id = id;
        this.name = name;
        this.inn = inn;
        this.settlementAcc = settlementAcc;
    }

    public Long getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public Long getInn() {
        return this.inn;
    }

    public Long getSettlementAcc() {
        return this.settlementAcc;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organizations (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(inn);
        sb.append(", ").append(settlementAcc);

        sb.append(")");
        return sb.toString();
    }
}
