/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Positions implements Serializable {

    private static final long serialVersionUID = 1681270900;

    private final Long nomenclatureId;
    private final Long waybillId;
    private final Long price;
    private final Long amount;

    public Positions(Positions value) {
        this.nomenclatureId = value.nomenclatureId;
        this.waybillId = value.waybillId;
        this.price = value.price;
        this.amount = value.amount;
    }

    public Positions(
        Long nomenclatureId,
        Long waybillId,
        Long price,
        Long amount
    ) {
        this.nomenclatureId = nomenclatureId;
        this.waybillId = waybillId;
        this.price = price;
        this.amount = amount;
    }

    public Long getNomenclatureId() {
        return this.nomenclatureId;
    }

    public Long getWaybillId() {
        return this.waybillId;
    }

    public Long getPrice() {
        return this.price;
    }

    public Long getAmount() {
        return this.amount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Positions (");

        sb.append(nomenclatureId);
        sb.append(", ").append(waybillId);
        sb.append(", ").append(price);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
