/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waybills implements Serializable {

    private static final long serialVersionUID = 195114575;

    private final Long orgSendId;
    private final Long number;
    private final Date date;

    public Waybills(Waybills value) {
        this.orgSendId = value.orgSendId;
        this.number = value.number;
        this.date = value.date;
    }

    public Waybills(
        Long orgSendId,
        Long number,
        Date date
    ) {
        this.orgSendId = orgSendId;
        this.number = number;
        this.date = date;
    }

    public Long getOrgSendId() {
        return this.orgSendId;
    }

    public Long getNumber() {
        return this.number;
    }

    public Date getDate() {
        return this.date;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Waybills (");

        sb.append(orgSendId);
        sb.append(", ").append(number);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
}
