/*
 * This file is generated by jOOQ.
 */
package db.tables;


import db.Indexes;
import db.Keys;
import db.Public;
import db.tables.records.PositionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Positions extends TableImpl<PositionsRecord> {

    private static final long serialVersionUID = -2007783388;

    /**
     * The reference instance of <code>public.positions</code>
     */
    public static final Positions POSITIONS = new Positions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PositionsRecord> getRecordType() {
        return PositionsRecord.class;
    }

    /**
     * The column <code>public.positions.nomenclature_id</code>.
     */
    public final TableField<PositionsRecord, Long> NOMENCLATURE_ID = createField("nomenclature_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.positions.waybill_id</code>.
     */
    public final TableField<PositionsRecord, Long> WAYBILL_ID = createField("waybill_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.positions.price</code>.
     */
    public final TableField<PositionsRecord, Long> PRICE = createField("price", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.positions.amount</code>.
     */
    public final TableField<PositionsRecord, Long> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.positions</code> table reference
     */
    public Positions() {
        this(DSL.name("positions"), null);
    }

    /**
     * Create an aliased <code>public.positions</code> table reference
     */
    public Positions(String alias) {
        this(DSL.name(alias), POSITIONS);
    }

    /**
     * Create an aliased <code>public.positions</code> table reference
     */
    public Positions(Name alias) {
        this(alias, POSITIONS);
    }

    private Positions(Name alias, Table<PositionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Positions(Name alias, Table<PositionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Positions(Table<O> child, ForeignKey<O, PositionsRecord> key) {
        super(child, key, POSITIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POSITIONS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PositionsRecord> getPrimaryKey() {
        return Keys.POSITIONS_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PositionsRecord>> getKeys() {
        return Arrays.<UniqueKey<PositionsRecord>>asList(Keys.POSITIONS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PositionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PositionsRecord, ?>>asList(Keys.POSITIONS__POSITIONS_FK0, Keys.POSITIONS__POSITIONS_FK1);
    }

    public Nomenclature nomenclature() {
        return new Nomenclature(this, Keys.POSITIONS__POSITIONS_FK0);
    }

    public Waybills waybills() {
        return new Waybills(this, Keys.POSITIONS__POSITIONS_FK1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Positions as(String alias) {
        return new Positions(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Positions as(Name alias) {
        return new Positions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Positions rename(String name) {
        return new Positions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Positions rename(Name name) {
        return new Positions(name, null);
    }
}
