/*
 * This file is generated by jOOQ.
 */
package db.tables.daos;


import db.tables.Organizations;
import db.tables.records.OrganizationsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationsDao extends DAOImpl<OrganizationsRecord, db.tables.pojos.Organizations, Long> {

    /**
     * Create a new OrganizationsDao without any configuration
     */
    public OrganizationsDao() {
        super(Organizations.ORGANIZATIONS, db.tables.pojos.Organizations.class);
    }

    /**
     * Create a new OrganizationsDao with an attached configuration
     */
    public OrganizationsDao(Configuration configuration) {
        super(Organizations.ORGANIZATIONS, db.tables.pojos.Organizations.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(db.tables.pojos.Organizations object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<db.tables.pojos.Organizations> fetchById(Long... values) {
        return fetch(Organizations.ORGANIZATIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public db.tables.pojos.Organizations fetchOneById(Long value) {
        return fetchOne(Organizations.ORGANIZATIONS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<db.tables.pojos.Organizations> fetchByName(String... values) {
        return fetch(Organizations.ORGANIZATIONS.NAME, values);
    }

    /**
     * Fetch records that have <code>inn IN (values)</code>
     */
    public List<db.tables.pojos.Organizations> fetchByInn(Long... values) {
        return fetch(Organizations.ORGANIZATIONS.INN, values);
    }

    /**
     * Fetch records that have <code>settlement_acc IN (values)</code>
     */
    public List<db.tables.pojos.Organizations> fetchBySettlementAcc(Long... values) {
        return fetch(Organizations.ORGANIZATIONS.SETTLEMENT_ACC, values);
    }
}
