/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.FlywaySchemaHistory;
import db.tables.Nomenclature;
import db.tables.Organizations;
import db.tables.Positions;
import db.tables.Waybills;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.nomenclature</code>.
     */
    public static final Nomenclature NOMENCLATURE = db.tables.Nomenclature.NOMENCLATURE;

    /**
     * The table <code>public.organizations</code>.
     */
    public static final Organizations ORGANIZATIONS = db.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.positions</code>.
     */
    public static final Positions POSITIONS = db.tables.Positions.POSITIONS;

    /**
     * The table <code>public.waybills</code>.
     */
    public static final Waybills WAYBILLS = db.tables.Waybills.WAYBILLS;
}
